name: CI (Quanta disabled)

on:
  push:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  pull_request:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  schedule:
    # Run against the last commit on the default branch on Friday at 8pm (UTC?)
    - cron: '0 20 * * 5'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # https://github.com/marketplace/actions/skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      # Continue running other jobs in the matrix even if one fails.
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - 1.60.0  # MSRV
          - nightly # For checking minimum version dependencies.

    steps:
      - name: Checkout Moka
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - name: cargo clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Downgrade dependencies to minimal versions (Nightly only)
        uses: actions-rs/cargo@v1
        if: ${{ matrix.rust == 'nightly' }}
        with:
          command: update
          args: -Z minimal-versions

      - name: Pin some dependencies to specific versions (Nightly only)
        if: ${{ matrix.rust == 'nightly' }}
        run: ./.ci_extras/pin-crate-vers-nightly.sh

      - name: Pin some dependencies to specific versions (MSRV only)
        if: ${{ matrix.rust == '1.60.0' }}
        run: ./.ci_extras/pin-crate-vers-msrv.sh

      - name: Run tests (debug, but no quanta feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features 'sync, atomic64'
        env:
          RUSTFLAGS: '--cfg rustver'

      - name: Run tests (release, but no quanta feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --no-default-features --features 'sync, atomic64'
        env:
          RUSTFLAGS: '--cfg rustver'

      - name: Run tests (future feature, but no quanta and sync features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features 'future, atomic64'

      - name: Run tests (future, sync and logging features, but no quanta feature)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features 'sync, future, atomic64, logging'
