name: Skeptic and Trybuild

on:
  push:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  schedule:
    # Run against the last commit on the default branch on Friday at 9pm (UTC?)
    - cron:  '0 21 * * 5'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # https://github.com/marketplace/actions/skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - name: Checkout Moka
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests (no features)
        run: cargo test --release
        env:
          RUSTFLAGS: '--cfg skeptic'

      - name: Run tests (release, sync and future)
        run: cargo test --release --features 'sync, future'
        env:
          RUSTFLAGS: '--cfg skeptic'

      - name: Run tests (sync and future, without atomic64 and quanta)
        run: cargo test --release --no-default-features --features 'sync, future'
        env:
          RUSTFLAGS: '--cfg skeptic'

      - name: Run compile error tests (sync and future features, trybuild)
        if: ${{ matrix.rust == 'stable' }}
        run: cargo test ui_trybuild --release --features 'sync, future'
        env:
          RUSTFLAGS: '--cfg trybuild'
